import course_img from "../../assets/images/ai-academy_img1.jpg";

export const courseData = [
  {
    id: 1,
    title: "Data Engineering",
    type: "Specialization",
    description:
      "Build strong foundations in data engineering by working on real-life projects, from ETL pipelines to designing scalable data warehouses.",
    image: course_img,
    collaborators: [
      { name: "AI-Academy", logo: openai },
      { name: "AWS", logo: AWS },
    ],
  },
  {
    id: 2,
    title: "AI Python for Beginners",
    type: "Short Course",
    description:
      "This course introduces Python for AI, covering the basics of data structures, libraries like NumPy and Pandas, and building your first AI models.",
    image: course_img,
    collaboratorName: "OpenAI",
    collaboratorLogo: openai,
  },
  {
    id: 3,
    title: "Generative AI for Software Development",
    type: "Specialization",
    description:
      "Master the tools and techniques for integrating generative AI into software projects. Learn about LLMs, prompt engineering, and practical deployments.",
    image: course_img,
    collaboratorName: "Meta",
    collaboratorLogo: openai,
  },
  {
    id: 4,
    title: "DSPy: Build and Optimize Agentic Apps",
    type: "Short Course",
    description:
      "Dive deep into DSPy to build and optimize agentic applications. From architecture to deployment, get hands-on with powerful AI workflows.",
    image: course_img,
    collaboratorName: "AI-Academy",
    collaboratorLogo: openai,
  },
  {
    id: 5,
    title: "Orchestrating Workflows for GenAI Applications",
    type: "Course",
    description:
      "Understand and implement orchestration patterns for GenAI applications. Work with modern tools to create robust and scalable AI workflows.",
    image: course_img,
    collaboratorName: "Stanford Online",
    collaboratorLogo: openai,
  },
  {
    id: 6,
    title: "Getting Structured LLM Output",
    type: "Specialization",
    description:
      "Learn how to design prompts and integrate APIs to ensure structured outputs from large language models for your projects.",
    image: course_img,
    collaboratorName: "Hugging Face",
    collaboratorLogo: huggingface,
  },

  // 🆕 Additional courses
  {
    id: 7,
    title: "Advanced Prompt Engineering",
    type: "Short Course",
    description:
      "Explore advanced techniques in prompt engineering and design effective AI workflows.",
    image: course_img,
    collaboratorName: "OpenAI",
    collaboratorLogo: openai,
  },
  {
    id: 8,
    title: "AI for Business Leaders",
    type: "Course",
    description:
      "Equip yourself with the knowledge to leverage AI in strategic business decisions.",
    image: course_img,
    collaboratorName: "AWS",
    collaboratorLogo: AWS,
  },
  {
    id: 9,
    title: "Machine Learning Foundations",
    type: "Specialization",
    description:
      "Cover machine learning basics, including supervised and unsupervised learning techniques.",
    image: course_img,
    collaboratorName: "Meta",
    collaboratorLogo: openai,
  },
  {
    id: 10,
    title: "Full Stack AI Applications",
    type: "Short Course",
    description:
      "Learn how to integrate AI into full stack applications with React and Django.",
    image: course_img,
    collaboratorName: "AI-Academy",
    collaboratorLogo: openai,
  },
  {
    id: 11,
    title: "Natural Language Processing Essentials",
    type: "Course",
    description:
      "Get started with NLP techniques like tokenization, embeddings, and transformers.",
    image: course_img,
    collaboratorName: "Hugging Face",
    collaboratorLogo: huggingface,
  },
  {
    id: 12,
    title: "Deep Learning with TensorFlow",
    type: "Specialization",
    description:
      "Master deep learning with hands-on TensorFlow projects and model optimization.",
    image: course_img,
    collaboratorName: "Stanford Online",
    collaboratorLogo: openai,
  },
  {
    id: 13,
    title: "AI Security Best Practices",
    type: "Short Course",
    description:
      "Learn how to secure AI applications and manage risks in deployment.",
    image: course_img,
    collaboratorName: "AWS",
    collaboratorLogo: AWS,
  },
  {
    id: 14,
    title: "Ethics in Artificial Intelligence",
    type: "Course",
    description:
      "Understand ethical considerations in building and deploying AI solutions.",
    image: course_img,
    collaboratorName: "OpenAI",
    collaboratorLogo: openai,
  },
  {
    id: 15,
    title: "Reinforcement Learning Basics",
    type: "Specialization",
    description:
      "Dive into reinforcement learning with practical projects and case studies.",
    image: course_img,
    collaboratorName: "Meta",
    collaboratorLogo: openai,
  },
  {
    id: 16,
    title: "Cloud AI Deployment",
    type: "Short Course",
    description: "Learn to deploy AI models on AWS, Azure, and GCP platforms.",
    image: course_img,
    collaboratorName: "AWS",
    collaboratorLogo: AWS,
  },
  {
    id: 17,
    title: "Generative AI for Designers",
    type: "Course",
    description:
      "Learn how designers can use generative AI tools to enhance creativity.",
    image: course_img,
    collaboratorName: "Hugging Face",
    collaboratorLogo: huggingface,
  },
  {
    id: 18,
    title: "Big Data for AI",
    type: "Specialization",
    description:
      "Explore big data concepts and their integration with AI systems.",
    image: course_img,
    collaboratorName: "Stanford Online",
    collaboratorLogo: openai,
  },
  {
    id: 19,
    title: "AI in Healthcare",
    type: "Short Course",
    description:
      "Learn about AI applications in diagnostics, patient care, and drug discovery.",
    image: course_img,
    collaboratorName: "AI-Academy",
    collaboratorLogo: openai,
  },
  {
    id: 20,
    title: "Time Series Forecasting",
    type: "Course",
    description:
      "Master time series analysis techniques using Python libraries.",
    image: course_img,
    collaboratorName: "AWS",
    collaboratorLogo: AWS,
  },
  {
    id: 21,
    title: "Conversational AI with Chatbots",
    type: "Specialization",
    description: "Design and build intelligent chatbots with NLP techniques.",
    image: course_img,
    collaboratorName: "Hugging Face",
    collaboratorLogo: huggingface,
  },
  {
    id: 22,
    title: "Explainable AI (XAI)",
    type: "Short Course",
    description: "Learn to make AI systems transparent and interpretable.",
    image: course_img,
    collaboratorName: "Meta",
    collaboratorLogo: openai,
  },
  {
    id: 23,
    title: "AI for Edge Devices",
    type: "Course",
    description: "Deploy AI models efficiently on low-resource edge devices.",
    image: course_img,
    collaboratorName: "AWS",
    collaboratorLogo: AWS,
  },
  {
    id: 24,
    title: "Vision AI Applications",
    type: "Specialization",
    description:
      "Develop computer vision solutions for real-world applications.",
    image: course_img,
    collaboratorName: "Hugging Face",
    collaboratorLogo: huggingface,
  },
  {
    id: 25,
    title: "Applied Data Science",
    type: "Short Course",
    description: "Use data science techniques to solve real-world problems.",
    image: course_img,
    collaboratorName: "Stanford Online",
    collaboratorLogo: openai,
  },
  {
    id: 26,
    title: "AI Model Optimization",
    type: "Course",
    description: "Optimize and compress AI models for faster performance.",
    image: course_img,
    collaboratorName: "AI-Academy",
    collaboratorLogo: openai,
  },
  {
    id: 27,
    title: "Speech Recognition Systems",
    type: "Specialization",
    description: "Build speech-to-text systems and integrate voice interfaces.",
    image: course_img,
    collaboratorName: "OpenAI",
    collaboratorLogo: openai,
  },
  {
    id: 28,
    title: "AI for IoT",
    type: "Short Course",
    description: "Combine AI with IoT to create intelligent connected systems.",
    image: course_img,
    collaboratorName: "AWS",
    collaboratorLogo: AWS,
  },
  {
    id: 29,
    title: "Human-Centered AI",
    type: "Course",
    description:
      "Design AI systems with a focus on user experience and usability.",
    image: course_img,
    collaboratorName: "Meta",
    collaboratorLogo: openai,
  },
  {
    id: 30,
    title: "AI for Robotics",
    type: "Specialization",
    description: "Learn how AI powers autonomous robots and robotic systems.",
    image: course_img,
    collaboratorName: "Hugging Face",
    collaboratorLogo: huggingface,
  },
];

// collab logos

import AIForGoodlab from "../../assets/collab-logos/collab-AI-for-good-lab.png";
import AWS from "../../assets/collab-logos/collab-AWS.png";
import Cohere from "../../assets/collab-logos/collab-Cohere.png";
import coursera from "../../assets/collab-logos/collab-coursera.png";
import Google_Cloud from "../../assets/collab-logos/collab-Google_Cloud.png";
import huggingface from "../../assets/collab-logos/collab-huggingface.webp";
import Lamini from "../../assets/collab-logos/collab-Lamini.png";
import langchain from "../../assets/collab-logos/collab-langchain.png";
import microsoft from "../../assets/collab-logos/collab-microsoft.webp";
import openai from "../../assets/collab-logos/collab-openai.png";
import stanford from "../../assets/collab-logos/collab-stanford.webp";
import weights from "../../assets/collab-logos/collab-weights.png";
import Google from "../../assets/collab-logos/collab-Google.png";

export const collabLogos = [
  AIForGoodlab,
  AWS,
  Cohere,
  coursera,
  Google_Cloud,
  huggingface,
  Lamini,
  langchain,
  microsoft,
  openai,
  stanford,
  weights,
  Google,
];

//sidebar

export const topics = [
  "Agents",
  "AI Frameworks",
  "AI in Software Development",
  "AI Safety",
  "Anomaly Detection",
  "Chatbots",
  "Compression and Quantization",
  "Computer Vision",
  "Data Engineering",
  "Data Processing",
  "Deep Learning",
  "Diffusion Models",
  "Document Processing",
  "Embeddings",
  "Evaluation and Monitoring",
  "Event-Driven AI",
  "Fine-Tuning",
  "GenAI Applications",
  "Generative Models",
  "LLM Serving",
  "LLMOps",
  "Machine Learning",
  "Mathematical Foundations",
  "MLOps",
  "MultiModal",
  "NLP",
  "On-Device AI",
  "Prompt Engineering",
  "RAG",
  "Search and Retrieval",
  "Supervised Learning",
  "Synthetic Data",
  "Task Automation",
  "Time Series",
  "Transformers",
  "Unsupervised Learning",
  "Vector Databases",
];

export const collaborators = [
  "AGI Inc",
  "AI Dungeon",
  "AI21 labs",
  "Anthropic",
  "Arize AI",
  "Astronomer",
  "AWS",
  "Chroma",
  "CircleCI",
  'Co-authors of "Hands-On Large Language Models"',
  "Cohere",
  "Comet",
  "crewAI",
  "Databricks",
  "DeepLearning.AI",
  "DotTxt",
  "Flower Labs",
  "Giskard",
  "Google",
  "Google Cloud",
  "GuardrailsAI",
  "Haystack",
  "Hugging Face",
  "IBM Research's BeeAI",
  "Intel",
  "Lamini",
  "LangChain",
  "Letta",
  "Livekit, RealAvatar",
  "LlamaIndex",
  "Meta",
  "Microsoft",
  "Mistral AI",
  "MongoDB",
  "Neo4j",
  "NexusFlow",
  "OpenAI",
  "Penn State University",
  "Pinecone",
  "Predibase",
  "Qdrant",
  "Qualcomm",
  "Replit",
  "Stanford Online",
  "StatQuest",
  "Tavily",
  "Together AI",
  "TruEra",
  "University of Washington",
  "Unstructured",
  "Upstage",
  "Vectara",
  "Weaviate",
  "Weights and Biases",
  "WhyLabs",
  "Windsurf",
];
